### ISSUE TITLE
Some countries scripts produce non-combinable geoms

### ISSUE THREAD

**Issue by ar0ch** [sjbeckett/subregionalcovid19#42]
It looks like the following countries are non-combinable in flatgeobuf format: Czechia, South Africa, Algeria, Afghanistan, Ghana, Zimbabwe

I'm not entirely sure what causes this but when used in GLOBALMAP, these countries produce invalid fgb files.  They are readable by the `sf` package but not parseable by `leaflet.js`.  I have no solution at this time

**Comment by ar0ch** [comment]
Sorry for the delay, i can confirm that it's the mixing of geometry types.  If I make a combined map with just the offending countries, that is loadable.  And casting everything to MULTIPOLYGON also makes it loadable all together.

**Comment by sjbeckett** [comment]
Great!

**Comment by sjbeckett** [comment]
Have cast all geoms to MULTIPOLYGON.
