### ISSUE TITLE
Is a Google OAUTH token required?

### ISSUE THREAD

**Issue by ar0ch** [sjbeckett/subregionalcovid19#5]
I see the Venezuela data is coming from a Google Sheet.  Is this the official data source?  If Yes, is there an alternative access method?

If there is no alternative, for automation please setup a new gmail account specifically for accessing this data and provide the OAUTH token

**Comment by sjbeckett** [comment]
So I tried something a little different to that we discussed, as I don't think we need to give the authorization inside the function LoadPhilippines itself. 1) a token can be provided at a higher scope e.g. https://gargle.r-lib.org/articles/non-interactive-auth.html . 2) If no token found, the first googledrive function will prompt the user to provide authentication.

I removed the authentication steps from LoadPhilippines; and added an interactiveMode option to LoadCountries. If `interactiveMode==FALSE` there is a check to see if there is a googledrive token in place; and if there is no token, then LoadPhilippines is removed from the list of input countries to load from (if it is there).
